package com.foldworks.client.ui;

import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.BufferBuilder;
import com.mojang.blaze3d.vertex.BufferUploader;
import com.mojang.blaze3d.vertex.DefaultVertexFormat;
import com.mojang.blaze3d.vertex.Tesselator;
import com.mojang.blaze3d.vertex.VertexFormat;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.renderer.GameRenderer;
import net.minecraft.resources.ResourceLocation;
import org.joml.Matrix4f;

/**
 * Texture-backed widgets for the Foldworks Chest GUI.
 *
 * The atlas is generated by scripts/generate_chest_gui_atlas.py. Keep these
 * coordinates in sync with that script rather than hand-editing the PNG.
 */
public final class ChestGuiTextures {
    private static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath("foldworks", "textures/gui/chest.png");
    private static final int TEX_W = 256;
    private static final int TEX_H = 256;

    private static final Sprite PANEL = new Sprite(0, 168, 32, 32, 8);
    private static final Sprite PANEL_LIGHT = new Sprite(32, 168, 32, 32, 8);
    private static final Sprite PANEL_LIGHTER = new Sprite(64, 168, 32, 32, 8);
    private static final Sprite INSET = new Sprite(48, 0, 16, 16, 4);
    private static final Sprite PANEL_COMPACT = new Sprite(0, 0, 16, 16, 4);
    private static final Sprite PANEL_LIGHT_COMPACT = new Sprite(16, 0, 16, 16, 4);
    private static final Sprite PANEL_LIGHTER_COMPACT = new Sprite(32, 0, 16, 16, 4);

    private static final Sprite BUTTON_NORMAL = new Sprite(0, 24, 18, 18, 5);
    private static final Sprite BUTTON_HOVER = new Sprite(18, 24, 18, 18, 5);
    private static final Sprite BUTTON_SELECTED = new Sprite(36, 24, 18, 18, 5);
    private static final Sprite BUTTON_DISABLED = new Sprite(54, 24, 18, 18, 5);
    private static final Sprite BUTTON_GOLD = new Sprite(72, 24, 18, 18, 5);
    private static final Sprite BUTTON_DANGER = new Sprite(90, 24, 18, 18, 5);

    private static final Sprite SLOT = new Sprite(0, 48, 18, 18, 2);
    private static final Sprite SLOT_HOVER = new Sprite(18, 48, 18, 18, 2);
    private static final Sprite SLOT_SELECTED = new Sprite(36, 48, 18, 18, 2);
    private static final Sprite SLOT_LOCKED = new Sprite(54, 48, 18, 18, 2);

    private static final Sprite SCROLL_TRACK = new Sprite(0, 72, 7, 16, 3);
    private static final Sprite SCROLL_THUMB = new Sprite(8, 72, 7, 16, 3);
    private static final Sprite SWITCH_TRACK = new Sprite(24, 72, 34, 14, 3);
    private static final Sprite CHEVRON_DOWN = new Sprite(112, 48, 7, 7, 0);
    private static final Sprite CHEVRON_UP = new Sprite(120, 48, 7, 7, 0);
    private static final int UPGRADE_GLYPH_SIZE = 14;
    private static final Sprite UPGRADE_STORAGE = new Sprite(0, 128, 32, 32, 0);
    private static final Sprite UPGRADE_FLUID = new Sprite(32, 128, 32, 32, 0);
    private static final Sprite UPGRADE_NETWORK = new Sprite(64, 128, 32, 32, 0);
    private static final Sprite UPGRADE_ENERGY = new Sprite(96, 128, 32, 32, 0);
    private static final Sprite UPGRADE_STRESS = new Sprite(128, 128, 32, 32, 0);
    private static final Sprite UPGRADE_SUITE = new Sprite(160, 128, 32, 32, 0);
    private static final Sprite WHITE_PIXEL = new Sprite(0, 100, 1, 1, 0);

    private ChestGuiTextures() {
    }

    public enum ButtonState {
        NORMAL,
        HOVER,
        SELECTED,
        DISABLED,
        GOLD,
        DANGER
    }

    public static void scrim(GuiGraphics g, int width, int height, int color) {
        fill(g, 0, 0, width, height, color);
    }

    public static void shadow(GuiGraphics g, int x, int y, int w, int h) {
        fill(g, x + 3, y + 3, w, h, 0x551A1A1A);
    }

    public static void flat(GuiGraphics g, int x, int y, int w, int h, int color) {
        fill(g, x, y, w, h, color);
    }

    public static void hDivider(GuiGraphics g, int x, int y, int w) {
        if (w <= 0) return;
        g.fill(x, y, x + w, y + 1, Theme.uiColor(0xFFEDF4FA));
    }

    public static void vDivider(GuiGraphics g, int x, int y, int h) {
        if (h <= 0) return;
        g.fill(x, y, x + 1, y + h, Theme.uiColor(0xFFEDF4FA));
    }

    public static void panel(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL, x, y, w, h);
    }

    public static void panelLight(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL_LIGHT, x, y, w, h);
    }

    public static void panelLighter(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL_LIGHTER, x, y, w, h);
    }

    public static void panelCompact(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL_COMPACT, x, y, w, h);
    }

    public static void panelLightCompact(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL_LIGHT_COMPACT, x, y, w, h);
    }

    public static void panelLighterCompact(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL_LIGHTER_COMPACT, x, y, w, h);
    }

    public static void inset(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, INSET, x, y, w, h);
    }

    public static void button(GuiGraphics g, int x, int y, int w, int h, ButtonState state) {
        nineSlice(g, switch (state) {
            case HOVER -> BUTTON_HOVER;
            case SELECTED -> BUTTON_SELECTED;
            case DISABLED -> BUTTON_DISABLED;
            case GOLD -> BUTTON_GOLD;
            case DANGER -> BUTTON_DANGER;
            default -> BUTTON_NORMAL;
        }, x, y, w, h);
    }

    public static void slot(GuiGraphics g, int x, int y, boolean hovered) {
        slot(g, x, y, hovered, false, false);
    }

    public static void slot(GuiGraphics g, int x, int y, boolean hovered, boolean selected, boolean locked) {
        Sprite sprite = locked ? SLOT_LOCKED : selected ? SLOT_SELECTED : hovered ? SLOT_HOVER : SLOT;
        blit(g, x, y, sprite.w, sprite.h, sprite.u, sprite.v, sprite.w, sprite.h);
    }

    public static void scrollbar(GuiGraphics g, int x, int y, int w, int h, int thumbY, int thumbH) {
        if (w <= 0 || h <= 0) return;
        int radius = Math.max(1, Math.min(4, w / 2));
        Theme.fillRound(g, x, y, w, h, radius, 0xFFBFD8EC);
        Theme.fillRound(g, x + 1, y + 1, Math.max(0, w - 2), Math.max(0, h - 2),
                Math.max(0, radius - 1), 0xFFE7F2FB);
        if (w > 4 && h > 4) {
            fill(g, x + 2, y + 2, w - 4, h - 4, 0x55FFFFFF);
        }

        int safeThumbH = Math.max(8, Math.min(thumbH, Math.max(1, h - 2)));
        int safeThumbY = Math.max(y + 1, Math.min(thumbY, y + h - 1 - safeThumbH));
        Theme.fillRound(g, x + 1, safeThumbY, Math.max(1, w - 2), safeThumbH,
                Math.max(1, radius - 1), 0xFF6AADE0);
        if (w > 4 && safeThumbH > 4) {
            fill(g, x + 2, safeThumbY + 2, Math.max(0, w - 4), 1, 0x80FFFFFF);
        }
    }

    public static void switchTrack(GuiGraphics g, int x, int y) {
        blit(g, x, y, SWITCH_TRACK.w, SWITCH_TRACK.h, SWITCH_TRACK.u, SWITCH_TRACK.v, SWITCH_TRACK.w, SWITCH_TRACK.h);
    }

    public static void switchKnob(GuiGraphics g, int x, int y, boolean enabled) {
        int u = enabled ? 64 : 80;
        blit(g, x, y, 11, 8, u, 75, 11, 8);
    }

    public static void progress(GuiGraphics g, int x, int y, int w, int h, float ratio, int color) {
        if (w <= 0 || h <= 0) return;
        fill(g, x, y, w, h, 0xFFC4DAEB);
        fill(g, x + 1, y + 1, Math.max(0, w - 2), Math.max(0, h - 2), 0xFFE4F1FA);
        fill(g, x + 1, y + 1, Math.max(0, w - 2), 1, 0xF8FFFFFF);
        int innerW = Math.max(0, w - 4);
        int innerH = Math.max(0, h - 4);
        int fillW = Math.max(0, Math.min(innerW, Math.round(innerW * Math.max(0.0f, Math.min(1.0f, ratio)))));
        if (fillW <= 0 || innerH <= 0) return;
        fill(g, x + 2, y + 2, fillW, innerH, color);
        fill(g, x + 2, y + 2, fillW, 1, mixColor(color, 0xFFFFFFFF, 0.45f));
    }

    public static void fluidSwatch(GuiGraphics g, int x, int y, int color) {
        inset(g, x, y, 13, 13);
        fill(g, x + 2, y + 2, 9, 9, color);
        fill(g, x + 2, y + 2, 9, 1, 0xCCFFFFFF);
    }

    public static void chevronDown(GuiGraphics g, int centerX, int centerY) {
        blit(g, centerX - 3, centerY - 3, CHEVRON_DOWN.w, CHEVRON_DOWN.h, CHEVRON_DOWN.u, CHEVRON_DOWN.v, CHEVRON_DOWN.w, CHEVRON_DOWN.h);
    }

    public static void chevronUp(GuiGraphics g, int centerX, int centerY) {
        blit(g, centerX - 3, centerY - 3, CHEVRON_UP.w, CHEVRON_UP.h, CHEVRON_UP.u, CHEVRON_UP.v, CHEVRON_UP.w, CHEVRON_UP.h);
    }

    public static void upgradeGlyph(GuiGraphics g, UpgradeGlyph glyph, int x, int y) {
        Sprite sprite = switch (glyph) {
            case STORAGE -> UPGRADE_STORAGE;
            case FLUID -> UPGRADE_FLUID;
            case NETWORK -> UPGRADE_NETWORK;
            case ENERGY -> UPGRADE_ENERGY;
            case STRESS -> UPGRADE_STRESS;
            case SUITE -> UPGRADE_SUITE;
        };
        blit(g, x, y, UPGRADE_GLYPH_SIZE, UPGRADE_GLYPH_SIZE, sprite.u, sprite.v, sprite.w, sprite.h);
    }

    public enum UpgradeGlyph {
        STORAGE,
        FLUID,
        NETWORK,
        ENERGY,
        STRESS,
        SUITE
    }

    private static void nineSlice(GuiGraphics g, Sprite s, int x, int y, int w, int h) {
        if (w <= 0 || h <= 0) return;
        int b = Math.min(s.border, Math.min(w, h) / 2);
        if (b <= 0 || w <= b * 2 || h <= b * 2 || s.w <= b * 2 || s.h <= b * 2) {
            blit(g, x, y, w, h, s.u, s.v, s.w, s.h);
            return;
        }

        int centerW = w - b * 2;
        int centerH = h - b * 2;
        int srcCenterW = s.w - b * 2;
        int srcCenterH = s.h - b * 2;

        blit(g, x, y, b, b, s.u, s.v, b, b);
        blit(g, x + b, y, centerW, b, s.u + b, s.v, srcCenterW, b);
        blit(g, x + w - b, y, b, b, s.u + s.w - b, s.v, b, b);

        blit(g, x, y + b, b, centerH, s.u, s.v + b, b, srcCenterH);
        blit(g, x + b, y + b, centerW, centerH, s.u + b, s.v + b, srcCenterW, srcCenterH);
        blit(g, x + w - b, y + b, b, centerH, s.u + s.w - b, s.v + b, b, srcCenterH);

        blit(g, x, y + h - b, b, b, s.u, s.v + s.h - b, b, b);
        blit(g, x + b, y + h - b, centerW, b, s.u + b, s.v + s.h - b, srcCenterW, b);
        blit(g, x + w - b, y + h - b, b, b, s.u + s.w - b, s.v + s.h - b, b, b);
    }

    private static void blit(GuiGraphics g, int x, int y, int w, int h, int u, int v, int uw, int vh) {
        if (w <= 0 || h <= 0 || uw <= 0 || vh <= 0) return;
        tintedBlit(g, x, y, w, h, u, v, uw, vh, Theme.uiColor(0xFFFFFFFF));
    }

    private static void fill(GuiGraphics g, int x, int y, int w, int h, int color) {
        if (w <= 0 || h <= 0) return;
        g.fill(x, y, x + w, y + h, Theme.uiColor(color));
    }

    private static void tintedBlit(GuiGraphics g, int x, int y, int w, int h, int u, int v, int uw, int vh, int color) {
        if (w <= 0 || h <= 0 || uw <= 0 || vh <= 0) return;
        float a = ((color >> 24) & 0xFF) / 255.0f;
        float r = ((color >> 16) & 0xFF) / 255.0f;
        float gr = ((color >> 8) & 0xFF) / 255.0f;
        float b = (color & 0xFF) / 255.0f;

        float minU = u / (float) TEX_W;
        float maxU = (u + uw) / (float) TEX_W;
        float minV = v / (float) TEX_H;
        float maxV = (v + vh) / (float) TEX_H;

        RenderSystem.setShaderTexture(0, TEXTURE);
        RenderSystem.setShader(GameRenderer::getPositionTexColorShader);
        RenderSystem.enableBlend();
        Matrix4f matrix = g.pose().last().pose();
        BufferBuilder buffer = Tesselator.getInstance().begin(VertexFormat.Mode.QUADS, DefaultVertexFormat.POSITION_TEX_COLOR);
        buffer.addVertex(matrix, x, y, 0).setUv(minU, minV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x, y + h, 0).setUv(minU, maxV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x + w, y + h, 0).setUv(maxU, maxV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x + w, y, 0).setUv(maxU, minV).setColor(r, gr, b, a);
        BufferUploader.drawWithShader(buffer.buildOrThrow());
        RenderSystem.disableBlend();
    }

    private static int mixColor(int a, int b, float t) {
        t = Math.max(0.0f, Math.min(1.0f, t));
        int aa = (a >>> 24) & 0xFF;
        int ar = (a >>> 16) & 0xFF;
        int ag = (a >>> 8) & 0xFF;
        int ab = a & 0xFF;
        int ba = (b >>> 24) & 0xFF;
        int br = (b >>> 16) & 0xFF;
        int bg = (b >>> 8) & 0xFF;
        int bb = b & 0xFF;
        int ca = Math.round(aa + (ba - aa) * t);
        int cr = Math.round(ar + (br - ar) * t);
        int cg = Math.round(ag + (bg - ag) * t);
        int cb = Math.round(ab + (bb - ab) * t);
        return (ca << 24) | (cr << 16) | (cg << 8) | cb;
    }

    private record Sprite(int u, int v, int w, int h, int border) {
    }
}
