package com.pockethomestead.client.ui;

import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.BufferBuilder;
import com.mojang.blaze3d.vertex.BufferUploader;
import com.mojang.blaze3d.vertex.DefaultVertexFormat;
import com.mojang.blaze3d.vertex.Tesselator;
import com.mojang.blaze3d.vertex.VertexFormat;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.renderer.GameRenderer;
import net.minecraft.resources.ResourceLocation;
import org.joml.Matrix4f;

/**
 * Texture-backed widgets for the Homestead Tablet GUI.
 *
 * The atlas is generated by scripts/generate_homestead_tablet_gui_atlas.py.
 * Keep sprite coordinates here in sync with that script.
 */
public final class HomesteadTabletGuiTextures {
    private static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath("pockethomestead", "textures/gui/homestead_tablet.png");
    private static final int TEX_W = 512;
    private static final int TEX_H = 512;

    private static final Sprite PANEL = new Sprite(0, 0, 32, 32, 8);
    private static final Sprite PANEL_SOFT = new Sprite(32, 0, 32, 32, 8);
    private static final Sprite PANEL_SELECTED = new Sprite(96, 0, 32, 32, 8);
    private static final Sprite BUTTON = new Sprite(0, 40, 32, 24, 4);
    private static final Sprite BUTTON_PRIMARY = new Sprite(32, 40, 32, 24, 4);
    private static final Sprite BUTTON_DANGER = new Sprite(64, 40, 32, 24, 4);
    private static final Sprite BUTTON_DISABLED = new Sprite(96, 40, 32, 24, 4);
    private static final Sprite WHITE_PIXEL = new Sprite(0, 88, 1, 1, 0);

    private static final Sprite ICON_CREATE = new Sprite(0, 112, 32, 32, 0);
    private static final Sprite ICON_MANAGE = new Sprite(32, 112, 32, 32, 0);
    private static final Sprite ICON_PERMISSIONS = new Sprite(64, 112, 32, 32, 0);
    private static final Sprite ICON_PRODUCTION = new Sprite(96, 112, 32, 32, 0);
    private static final Sprite ICON_MIGRATION = new Sprite(128, 112, 32, 32, 0);
    private static final Sprite ICON_CLOSE = new Sprite(160, 112, 32, 32, 0);
    private static final Sprite ICON_TABLET_CHEST = new Sprite(0, 176, 32, 32, 0);

    private HomesteadTabletGuiTextures() {
    }

    public enum ButtonState {
        NORMAL,
        HOVER,
        SELECTED,
        DISABLED,
        DANGER
    }

    public enum Icon {
        CREATE,
        MANAGE,
        PERMISSIONS,
        PRODUCTION,
        MIGRATION,
        TABLET_CHEST,
        CLOSE
    }

    public static void shadow(GuiGraphics g, int x, int y, int w, int h) {
        fill(g, x + 2, y + 3, w, h, 0x300F2236);
        fill(g, x + 4, y + 5, w, h, 0x180F2236);
    }

    public static void panel(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL, x, y, w, h);
    }

    public static void panelSoft(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL_SOFT, x, y, w, h);
    }

    public static void panelSelected(GuiGraphics g, int x, int y, int w, int h) {
        nineSlice(g, PANEL_SELECTED, x, y, w, h);
    }

    public static void button(GuiGraphics g, int x, int y, int w, int h, ButtonState state) {
        Sprite sprite = switch (state) {
            case HOVER -> BUTTON_PRIMARY;
            case SELECTED -> BUTTON_PRIMARY;
            case DISABLED -> BUTTON_DISABLED;
            case DANGER -> BUTTON_DANGER;
            default -> BUTTON;
        };
        nineSlice(g, sprite, x, y, w, h);
    }

    public static void icon(GuiGraphics g, Icon icon, int x, int y, int size) {
        Sprite sprite = switch (icon) {
            case CREATE -> ICON_CREATE;
            case MANAGE -> ICON_MANAGE;
            case PERMISSIONS -> ICON_PERMISSIONS;
            case PRODUCTION -> ICON_PRODUCTION;
            case MIGRATION -> ICON_MIGRATION;
            case TABLET_CHEST -> ICON_TABLET_CHEST;
            case CLOSE -> ICON_CLOSE;
        };
        blit(g, x, y, size, size, sprite.u, sprite.v, sprite.w, sprite.h);
    }

    public static void hDivider(GuiGraphics g, int x, int y, int w) {
        fill(g, x, y, w, 1, 0xFFEDF4FA);
    }

    public static void vDivider(GuiGraphics g, int x, int y, int h) {
        fill(g, x, y, 1, h, 0xFFEDF4FA);
    }

    private static void nineSlice(GuiGraphics g, Sprite s, int x, int y, int w, int h) {
        if (w <= 0 || h <= 0) return;
        int b = Math.min(s.border, Math.min(w, h) / 2);
        if (b <= 0 || w <= b * 2 || h <= b * 2 || s.w <= b * 2 || s.h <= b * 2) {
            blit(g, x, y, w, h, s.u, s.v, s.w, s.h);
            return;
        }

        int centerW = w - b * 2;
        int centerH = h - b * 2;
        int srcCenterW = s.w - b * 2;
        int srcCenterH = s.h - b * 2;

        blit(g, x, y, b, b, s.u, s.v, b, b);
        blit(g, x + b, y, centerW, b, s.u + b, s.v, srcCenterW, b);
        blit(g, x + w - b, y, b, b, s.u + s.w - b, s.v, b, b);

        blit(g, x, y + b, b, centerH, s.u, s.v + b, b, srcCenterH);
        blit(g, x + b, y + b, centerW, centerH, s.u + b, s.v + b, srcCenterW, srcCenterH);
        blit(g, x + w - b, y + b, b, centerH, s.u + s.w - b, s.v + b, b, srcCenterH);

        blit(g, x, y + h - b, b, b, s.u, s.v + s.h - b, b, b);
        blit(g, x + b, y + h - b, centerW, b, s.u + b, s.v + s.h - b, srcCenterW, b);
        blit(g, x + w - b, y + h - b, b, b, s.u + s.w - b, s.v + s.h - b, b, b);
    }

    private static void blit(GuiGraphics g, int x, int y, int w, int h, int u, int v, int uw, int vh) {
        if (w <= 0 || h <= 0 || uw <= 0 || vh <= 0) return;
        tintedBlit(g, x, y, w, h, u, v, uw, vh, Theme.uiColor(0xFFFFFFFF));
    }

    private static void fill(GuiGraphics g, int x, int y, int w, int h, int color) {
        tintedBlit(g, x, y, w, h, WHITE_PIXEL.u, WHITE_PIXEL.v, WHITE_PIXEL.w, WHITE_PIXEL.h, Theme.uiColor(color));
    }

    private static void tintedBlit(GuiGraphics g, int x, int y, int w, int h, int u, int v, int uw, int vh, int color) {
        if (w <= 0 || h <= 0 || uw <= 0 || vh <= 0) return;
        float a = ((color >> 24) & 0xFF) / 255.0f;
        float r = ((color >> 16) & 0xFF) / 255.0f;
        float gr = ((color >> 8) & 0xFF) / 255.0f;
        float b = (color & 0xFF) / 255.0f;

        float minU = u / (float) TEX_W;
        float maxU = (u + uw) / (float) TEX_W;
        float minV = v / (float) TEX_H;
        float maxV = (v + vh) / (float) TEX_H;

        RenderSystem.setShaderTexture(0, TEXTURE);
        RenderSystem.setShader(GameRenderer::getPositionTexColorShader);
        RenderSystem.enableBlend();
        Matrix4f matrix = g.pose().last().pose();
        BufferBuilder buffer = Tesselator.getInstance().begin(VertexFormat.Mode.QUADS, DefaultVertexFormat.POSITION_TEX_COLOR);
        buffer.addVertex(matrix, x, y, 0).setUv(minU, minV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x, y + h, 0).setUv(minU, maxV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x + w, y + h, 0).setUv(maxU, maxV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x + w, y, 0).setUv(maxU, minV).setColor(r, gr, b, a);
        BufferUploader.drawWithShader(buffer.buildOrThrow());
        RenderSystem.disableBlend();
    }

    private record Sprite(int u, int v, int w, int h, int border) {
    }
}
