package com.pockethomestead.client.ui;

import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.BufferBuilder;
import com.mojang.blaze3d.vertex.BufferUploader;
import com.mojang.blaze3d.vertex.DefaultVertexFormat;
import com.mojang.blaze3d.vertex.Tesselator;
import com.mojang.blaze3d.vertex.VertexFormat;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.renderer.GameRenderer;
import net.minecraft.resources.ResourceLocation;
import org.joml.Matrix4f;

/**
 * Texture-backed widgets for the transfer graph screen.
 * The atlas is generated by scripts/generate_transfer_graph_gui_atlas.py.
 */
public final class TransferGraphGuiTextures {
    private static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath("pockethomestead", "textures/gui/transfer_graph.png");
    private static final int TEX_SCALE = 8;
    private static final int TEX_W = 4096;
    private static final int TEX_H = 4096;

    private static final Sprite PANEL = new Sprite(0, 0, 24, 24, 8);
    private static final Sprite PANEL_SOFT = new Sprite(24, 0, 24, 24, 8);
    private static final Sprite PANEL_SELECTED = new Sprite(48, 0, 24, 24, 8);
    private static final Sprite PANEL_DANGER = new Sprite(72, 0, 24, 24, 8);
    private static final Sprite PANEL_DISABLED = new Sprite(96, 0, 24, 24, 8);
    private static final Sprite FIELD = new Sprite(120, 0, 24, 24, 8);

    private static final Sprite HEADER_BLUE = new Sprite(0, 32, 24, 16, 8);
    private static final Sprite HEADER_CYAN = new Sprite(24, 32, 24, 16, 8);
    private static final Sprite HEADER_PINK = new Sprite(48, 32, 24, 16, 8);
    private static final Sprite HEADER_DISABLED = new Sprite(72, 32, 24, 16, 8);

    private static final Sprite BUTTON = new Sprite(0, 56, 26, 24, 8);
    private static final Sprite BUTTON_BLUE = new Sprite(26, 56, 26, 24, 8);
    private static final Sprite BUTTON_PINK = new Sprite(52, 56, 26, 24, 8);
    private static final Sprite BUTTON_DISABLED = new Sprite(78, 56, 26, 24, 8);
    private static final Sprite BUTTON_SELECTED = new Sprite(104, 56, 26, 24, 8);
    private static final Sprite GRID_TILE = new Sprite(152, 0, 72, 72, 0);
    private static final Sprite WHITE_PIXEL = new Sprite(0, 88, 1, 1, 0);

    private static final Sprite ICON_SAVE = new Sprite(0, 256, 64, 64, 0);
    private static final Sprite ICON_PAGE = new Sprite(64, 256, 64, 64, 0);
    private static final Sprite ICON_PLUS = new Sprite(128, 256, 64, 64, 0);
    private static final Sprite ICON_HELP = new Sprite(192, 256, 64, 64, 0);
    private static final Sprite ICON_CLOSE = new Sprite(256, 256, 64, 64, 0);
    private static final Sprite ICON_CHEVRON_DOWN = new Sprite(320, 256, 64, 64, 0);
    private static final Sprite ICON_CHEVRON_RIGHT = new Sprite(384, 256, 64, 64, 0);
    private static final Sprite ICON_CHEST = new Sprite(0, 120, 18, 18, 0);
    private static final Sprite ICON_REROUTE = new Sprite(22, 120, 18, 18, 0);
    private static final Sprite ICON_BACKPACK = new Sprite(46, 120, 18, 18, 0);
    private static final Sprite ICON_TRASH = new Sprite(70, 120, 18, 18, 0);
    private static final Sprite ICON_LIMIT_GATE = new Sprite(94, 120, 18, 18, 0);
    private static final Sprite ICON_JUMP_IN = new Sprite(118, 120, 18, 18, 0);
    private static final Sprite ICON_JUMP_OUT = new Sprite(142, 120, 18, 18, 0);
    private static final Sprite ICON_ITEM = new Sprite(0, 144, 18, 20, 0);
    private static final Sprite ICON_FLUID = new Sprite(22, 144, 18, 20, 0);
    private static final Sprite ICON_ENERGY = new Sprite(44, 144, 18, 20, 0);
    private static final Sprite ICON_STRESS = new Sprite(66, 144, 18, 20, 0);

    private TransferGraphGuiTextures() {
    }

    public enum PanelStyle {
        NORMAL,
        SOFT,
        SELECTED,
        DANGER,
        DISABLED,
        FIELD
    }

    public enum HeaderStyle {
        BLUE,
        CYAN,
        PINK,
        DISABLED
    }

    public enum ButtonStyle {
        NORMAL,
        BLUE,
        PINK,
        DISABLED,
        SELECTED
    }

    public enum Icon {
        SAVE,
        PAGE,
        PLUS,
        HELP,
        CLOSE,
        CHEVRON_DOWN,
        CHEVRON_RIGHT,
        CHEST,
        REROUTE,
        BACKPACK,
        TRASH,
        LIMIT_GATE,
        JUMP_IN,
        JUMP_OUT,
        ITEM,
        FLUID,
        ENERGY,
        STRESS
    }

    public static void canvasBackground(GuiGraphics g, int width, int height, int panX, int panY, double zoom) {
        fill(g, 0, 0, width, height, 0xFFFDFEFF);
        int grid = Math.max(56, (int) Math.round(72 * Math.max(0.75, Math.min(1.35, zoom))));
        int minor = Math.max(28, grid / 2);
        int startX = Math.floorMod(panX, minor) - minor;
        int startY = Math.floorMod(panY, minor) - minor;
        for (int x = startX; x < width; x += minor) {
            fill(g, x, 0, 1, height, Math.floorMod(x - panX, grid) == 0 ? 0x2EB7D7EE : 0x1DD9EAF6);
        }
        for (int y = startY; y < height; y += minor) {
            fill(g, 0, y, width, 1, Math.floorMod(y - panY, grid) == 0 ? 0x2EB7D7EE : 0x1DD9EAF6);
        }
    }

    public static void shadow(GuiGraphics g, int x, int y, int w, int h) {
        fill(g, x + 3, y + 4, w, h, 0x1F405E78);
        fill(g, x + 1, y + 2, w, h, 0x102A4860);
    }

    public static void panel(GuiGraphics g, int x, int y, int w, int h, PanelStyle style) {
        nineSlice(g, panelSprite(style), x, y, w, h);
    }

    public static void header(GuiGraphics g, int x, int y, int w, int h, HeaderStyle style) {
        nineSlice(g, switch (style) {
            case CYAN -> HEADER_CYAN;
            case PINK -> HEADER_PINK;
            case DISABLED -> HEADER_DISABLED;
            default -> HEADER_BLUE;
        }, x, y, w, h);
    }

    public static void button(GuiGraphics g, int x, int y, int w, int h, ButtonStyle style) {
        nineSlice(g, switch (style) {
            case BLUE -> BUTTON_BLUE;
            case PINK -> BUTTON_PINK;
            case DISABLED -> BUTTON_DISABLED;
            case SELECTED -> BUTTON_SELECTED;
            default -> BUTTON;
        }, x, y, w, h);
    }

    public static void icon(GuiGraphics g, Icon icon, int x, int y) {
        Sprite s = switch (icon) {
            case SAVE -> ICON_SAVE;
            case PAGE -> ICON_PAGE;
            case PLUS -> ICON_PLUS;
            case HELP -> ICON_HELP;
            case CLOSE -> ICON_CLOSE;
            case CHEVRON_DOWN -> ICON_CHEVRON_DOWN;
            case CHEVRON_RIGHT -> ICON_CHEVRON_RIGHT;
            case CHEST -> ICON_CHEST;
            case REROUTE -> ICON_REROUTE;
            case BACKPACK -> ICON_BACKPACK;
            case TRASH -> ICON_TRASH;
            case LIMIT_GATE -> ICON_LIMIT_GATE;
            case JUMP_IN -> ICON_JUMP_IN;
            case JUMP_OUT -> ICON_JUMP_OUT;
            case ITEM -> ICON_ITEM;
            case FLUID -> ICON_FLUID;
            case ENERGY -> ICON_ENERGY;
            case STRESS -> ICON_STRESS;
        };
        int display = s.w == 64 && s.h == 64 ? 18 : s.w;
        blit(g, x, y, display, display, s.u, s.v, s.w, s.h);
    }

    public static void icon(GuiGraphics g, Icon icon, int x, int y, int size) {
        Sprite s = switch (icon) {
            case SAVE -> ICON_SAVE;
            case PAGE -> ICON_PAGE;
            case PLUS -> ICON_PLUS;
            case HELP -> ICON_HELP;
            case CLOSE -> ICON_CLOSE;
            case CHEVRON_DOWN -> ICON_CHEVRON_DOWN;
            case CHEVRON_RIGHT -> ICON_CHEVRON_RIGHT;
            case CHEST -> ICON_CHEST;
            case REROUTE -> ICON_REROUTE;
            case BACKPACK -> ICON_BACKPACK;
            case TRASH -> ICON_TRASH;
            case LIMIT_GATE -> ICON_LIMIT_GATE;
            case JUMP_IN -> ICON_JUMP_IN;
            case JUMP_OUT -> ICON_JUMP_OUT;
            case ITEM -> ICON_ITEM;
            case FLUID -> ICON_FLUID;
            case ENERGY -> ICON_ENERGY;
            case STRESS -> ICON_STRESS;
        };
        blit(g, x, y, size, size, s.u, s.v, s.w, s.h);
    }

    public static void port(GuiGraphics g, int centerX, int centerY, int color) {
        panel(g, centerX - 6, centerY - 6, 12, 12, PanelStyle.NORMAL);
        fill(g, centerX - 3, centerY - 3, 6, 6, color);
    }

    public static void progress(GuiGraphics g, int x, int y, int w, int h, float ratio, int color) {
        panel(g, x, y, w, h, PanelStyle.FIELD);
        int innerW = Math.max(0, w - 3);
        int innerH = Math.max(0, h - 3);
        int fillW = Math.max(0, Math.min(innerW, Math.round(innerW * Math.max(0.0f, Math.min(1.0f, ratio)))));
        if (fillW <= 0 || innerH <= 0) return;
        fill(g, x + 2, y + 2, fillW, innerH, color);
        fill(g, x + 2, y + 2, fillW, 1, 0x99FFFFFF);
    }

    public static void dividerH(GuiGraphics g, int x, int y, int w) {
        fill(g, x, y, w, 1, 0xFFE7F0F8);
    }

    public static void fillRect(GuiGraphics g, int x, int y, int w, int h, int color) {
        fill(g, x, y, w, h, color);
    }

    private static Sprite panelSprite(PanelStyle style) {
        return switch (style) {
            case SOFT -> PANEL_SOFT;
            case SELECTED -> PANEL_SELECTED;
            case DANGER -> PANEL_DANGER;
            case DISABLED -> PANEL_DISABLED;
            case FIELD -> FIELD;
            default -> PANEL;
        };
    }

    private static void nineSlice(GuiGraphics g, Sprite s, int x, int y, int w, int h) {
        if (w <= 0 || h <= 0) return;
        int b = Math.min(s.border, Math.min(w, h) / 2);
        if (b <= 0 || w <= b * 2 || h <= b * 2 || s.w <= b * 2 || s.h <= b * 2) {
            blit(g, x, y, w, h, s.u, s.v, s.w, s.h);
            return;
        }
        int cw = w - b * 2;
        int ch = h - b * 2;
        int scw = s.w - b * 2;
        int sch = s.h - b * 2;

        blit(g, x, y, b, b, s.u, s.v, b, b);
        blit(g, x + b, y, cw, b, s.u + b, s.v, scw, b);
        blit(g, x + w - b, y, b, b, s.u + s.w - b, s.v, b, b);

        blit(g, x, y + b, b, ch, s.u, s.v + b, b, sch);
        blit(g, x + b, y + b, cw, ch, s.u + b, s.v + b, scw, sch);
        blit(g, x + w - b, y + b, b, ch, s.u + s.w - b, s.v + b, b, sch);

        blit(g, x, y + h - b, b, b, s.u, s.v + s.h - b, b, b);
        blit(g, x + b, y + h - b, cw, b, s.u + b, s.v + s.h - b, scw, b);
        blit(g, x + w - b, y + h - b, b, b, s.u + s.w - b, s.v + s.h - b, b, b);
    }

    private static void blit(GuiGraphics g, int x, int y, int w, int h, int u, int v, int uw, int vh) {
        if (w <= 0 || h <= 0 || uw <= 0 || vh <= 0) return;
        tintedBlit(g, x, y, w, h, u, v, uw, vh, Theme.uiColor(0xFFFFFFFF));
    }

    private static void fill(GuiGraphics g, int x, int y, int w, int h, int color) {
        tintedBlit(g, x, y, w, h, WHITE_PIXEL.u, WHITE_PIXEL.v, WHITE_PIXEL.w, WHITE_PIXEL.h, Theme.uiColor(color));
    }

    private static void tintedBlit(GuiGraphics g, int x, int y, int w, int h, int u, int v, int uw, int vh, int color) {
        if (w <= 0 || h <= 0 || uw <= 0 || vh <= 0) return;
        float a = ((color >> 24) & 0xFF) / 255.0f;
        float r = ((color >> 16) & 0xFF) / 255.0f;
        float gr = ((color >> 8) & 0xFF) / 255.0f;
        float b = (color & 0xFF) / 255.0f;

        float minU = (u * TEX_SCALE) / (float) TEX_W;
        float maxU = ((u + uw) * TEX_SCALE) / (float) TEX_W;
        float minV = (v * TEX_SCALE) / (float) TEX_H;
        float maxV = ((v + vh) * TEX_SCALE) / (float) TEX_H;

        RenderSystem.setShaderTexture(0, TEXTURE);
        RenderSystem.setShader(GameRenderer::getPositionTexColorShader);
        RenderSystem.enableBlend();
        Matrix4f matrix = g.pose().last().pose();
        BufferBuilder buffer = Tesselator.getInstance().begin(VertexFormat.Mode.QUADS, DefaultVertexFormat.POSITION_TEX_COLOR);
        buffer.addVertex(matrix, x, y, 0).setUv(minU, minV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x, y + h, 0).setUv(minU, maxV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x + w, y + h, 0).setUv(maxU, maxV).setColor(r, gr, b, a);
        buffer.addVertex(matrix, x + w, y, 0).setUv(maxU, minV).setColor(r, gr, b, a);
        BufferUploader.drawWithShader(buffer.buildOrThrow());
        RenderSystem.disableBlend();
    }

    private record Sprite(int u, int v, int w, int h, int border) {
    }
}
